=== wilfreud/php-xml-web-portal/dtd/cinema.dtd
<!ELEMENT cinema(film+)>
<!ELEMENT film(titre, duree, genre, realisateur, acteurs,
anneeProduction, langue, presse?, spectateur?, description )>
<!ELEMENT titre(#PCDATA)>
<!ELEMENT duree(#PCDATA)>
<!ELEMENT genre(#PCDATA)>
<!ELEMENT realisateur(#PCDATA)>
<!ELEMENT acteurs(acteur+)>
<!ELEMENT acteur(#PCDATA)>
<!ELEMENT anneeProduction(#PCDATA)>
<!ELEMENT langue(#PCDATA)>
<!ELEMENT presse(#PCDATA)>
<!ELEMENT spectateur(#PCDATA)>
<!ELEMENT description(paragraphe)>
<!ELEMENT paragraphe(intrigue, horaires)>
<!ELEMENT intrigue(#PCDATA)>
<!ELEMENT horaires(horaire+)>
<!ELEMENT horaire(jour, heure)>
<!ATTLIST horaire id CDATA REQUIRED>
<!ELEMENT jour(Lundi | Mardi| Mercredi| Jeudi | Vendredi|Samedi|Dimanche)>
<!ELEMENT heure(10:20|14:00|16:40|19:40|20:20|22:10)>

=== wilfreud/php-xml-web-portal/xml/cinema.xml
<?xml version="1.0"?>
<!DOCTYPE cinema SYSTEM "dtd/cinema.dtd">
<cinema>
  <film>
    <titre>Les Brigades du Tigre</titre>
    <duree>2h 5min</duree>
    <genre>Policier</genre>
    <realisateur>J&#xE9;r&#xF4;me Cornuau</realisateur>
    <acteurs>
      <acteur>C. Cornillac</acteur>
      <acteur>D. Kruger</acteur>
      <acteur>E. Baer</acteur>
    </acteurs>
    <anneeProduction>2005</anneeProduction>
    <langue>en Fran&#xE7;ais</langue>
    <presse>3/5</presse>
    <spectateur>4/5</spectateur>
    <description>
      <paragraphe>
        <intrigue>Attaque Tigrine!</intrigue>
        <horaires>
          <horaire id="1">
            <jour>Mercredi | Samedi</jour>
            <heure>14:00 | 16:40 | 19:40 | 22:10</heure>
          </horaire>
          <horaire id="2">
            <jour>Jeudi | Vendredi | Lundi | Mardi</jour>
            <heure>14:00 | 19:40 | 22:10</heure>
          </horaire>
          <horaire id="3">
            <jour>Dimanche</jour>
            <heure>10:20 | 14:00 | 16:40 | 20:20</heure>
          </horaire>
        </horaires>
      </paragraphe>
    </description>
  </film>

  <film>
    <titre>Inception</titre>
    <duree>2h 28min</duree>
    <genre>Science-Fiction</genre>
    <realisateur>Christopher Nolan</realisateur>
    <acteurs>
      <acteur>Leonardo DiCaprio</acteur>
      <acteur>Joseph Gordon-Levitt</acteur>
      <acteur>Ellen Page</acteur>
    </acteurs>
    <anneeProduction>2010</anneeProduction>
    <langue>en Anglais</langue>
    <presse>4.5/5</presse>
    <spectateur>5/5</spectateur>
    <description>
      <paragraphe>
        <intrigue/>
        <horaires>
          <horaire id="1">
            <jour>Vendredi | Samedi</jour>
            <heure>14:30 | 17:00 | 19:30 | 22:00</heure>
          </horaire>
          <horaire id="2">
            <jour>Dimanche</jour>
            <heure>11:00 | 14:30 | 17:00 | 19:30</heure>
          </horaire>
        </horaires>
      </paragraphe>
    </description>
  </film>

  <film>
    <titre>Avatar</titre>
    <duree>2h 42min</duree>
    <genre>Fantasy</genre>
    <realisateur>James Cameron</realisateur>
    <acteurs>
      <acteur>Sam Worthington</acteur>
      <acteur>Zoe Saldana</acteur>
      <acteur>Sigourney Weaver</acteur>
    </acteurs>
    <anneeProduction>2009</anneeProduction>
    <langue>en Anglais</langue>
    <presse>4/5</presse>
    <spectateur>4.5/5</spectateur>
    <description>
      <paragraphe>
        <intrigue/>
        <horaires>
          <horaire id="1">
            <jour>Lundi | Mercredi</jour>
            <heure>14:00 | 17:00 | 20:00 | 23:00</heure>
          </horaire>
          <horaire id="2">
            <jour>Samedi | Dimanche</jour>
            <heure>11:00 | 14:00 | 17:00 | 20:00</heure>
          </horaire>
        </horaires>
      </paragraphe>
    </description>
  </film>

  <film>
    <titre>The Dark Knight</titre>
    <duree>2h 32min</duree>
    <genre>Action</genre>
    <realisateur>Christopher Nolan</realisateur>
    <acteurs>
      <acteur>Christian Bale</acteur>
      <acteur>Heath Ledger</acteur>
      <acteur>Aaron Eckhart</acteur>
    </acteurs>
    <anneeProduction>2008</anneeProduction>
    <langue>en Anglais</langue>
    <presse>5/5</presse>
    <spectateur>5/5</spectateur>
    <description>
      <paragraphe>
        <intrigue/>
        <horaires>
          <horaire id="1">
            <jour>Mardi | Jeudi</jour>
            <heure>15:00 | 18:00 | 21:00</heure>
          </horaire>
          <horaire id="2">
            <jour>Vendredi | Samedi</jour>
            <heure>13:00 | 16:00 | 19:00 | 22:00</heure>
          </horaire>
        </horaires>
      </paragraphe>
    </description>
  </film>

  <film>
    <titre>Titanic</titre>
    <duree>3h 15min</duree>
    <genre>Romance</genre>
    <realisateur>James Cameron</realisateur>
    <acteurs>
      <acteur>Leonardo DiCaprio</acteur>
      <acteur>Kate Winslet</acteur>
      <acteur>Billy Zane</acteur>
    </acteurs>
    <anneeProduction>1997</anneeProduction>
    <langue>en Anglais</langue>
    <presse>4.5/5</presse>
    <spectateur>5/5</spectateur>
    <description>
      <paragraphe>
        <intrigue/>
        <horaires>
          <horaire id="1">
            <jour>Samedi | Dimanche</jour>
            <heure>10:00 | 14:00 | 18:00 | 22:00</heure>
          </horaire>
          <horaire id="2">
            <jour>Mercredi | Vendredi</jour>
            <heure>12:00 | 16:00 | 20:00</heure>
          </horaire>
        </horaires>
      </paragraphe>
    </description>
  </film>

  <film>
    <titre>La La Land</titre>
    <duree>2h 8min</duree>
    <genre>Com&#xE9;die Musicale</genre>
    <realisateur>Damien Chazelle</realisateur>
    <acteurs>
      <acteur>Ryan Gosling</acteur>
      <acteur>Emma Stone</acteur>
      <acteur>John Legend</acteur>
    </acteurs>
    <anneeProduction>2016</anneeProduction>
    <langue>en Anglais</langue>
    <presse>4.5/5</presse>
    <spectateur>4.5/5</spectateur>
    <description>
      <paragraphe>
        <intrigue>Nein! English!</intrigue>
        <horaires>
          <horaire id="1">
            <jour>Vendredi | Samedi</jour>
            <heure>14:00 | 17:00 | 20:00 | 23:00</heure>
          </horaire>
          <horaire id="2">
            <jour>Lundi | Mardi</jour>
            <heure>14:00 | 17:00 | 20:00</heure>
          </horaire>
        </horaires>
      </paragraphe>
    </description>
  </film>
  <film>
    <titre>Interstellar</titre>
    <duree>2h 49mn</duree>
    <genre>Sci-FI</genre>
    <realisateur>Christopher Nollan</realisateur>
    <acteurs>
      <acteur>Mathew McConaughey</acteur>
      <acteur>Anne Hathaway</acteur>
      <acteur>Jessica Chastain</acteur>
    </acteurs>
    <anneeProduction>2014</anneeProduction>
    <langue>Anglais</langue>
    <presse>4.6/5</presse>
    <spectateur>4.8/5</spectateur>
    <description>
      <paragraphe>
        <intrigue>Un groupe d'explorateurs utilise un trou de ver r&#xE9;cemment d&#xE9;couvert pour
          surpasser les limites du voyage spatial humain et conqu&#xE9;rir les vastes distances
          impliqu&#xE9;es dans un voyage interstellaire.</intrigue>
        <horaires>
          <horaire id="66916c7cf1c99">
            <jour>Lundi|Mercredi|Vendredi</jour>
            <heure>13:00|16:30|20:00</heure>
          </horaire>
          <horaire id="66916c7cf1ca5">
            <jour>Samedi|Dimanche</jour>
            <heure>10:00|14:00|18:00</heure>
          </horaire>
        </horaires>
      </paragraphe>
    </description>
  </film>
<film><titre>Interstellar 2</titre><duree>2h 491mn</duree><genre>Sci-FI1</genre><realisateur>Christopher Nollanaa</realisateur><acteurs><acteur>Marie Curie</acteur><acteur>Pierre Niney</acteur><acteur>Qilbot</acteur></acteurs><anneeProduction>2054</anneeProduction><langue>Deutch</langue><presse>4.6/5</presse><spectateur>4.8/5</spectateur><description><paragraphe><intrigue>Lorep ipsum dolor sit amet</intrigue><horaires><horaire id="66916df97b038"><jour>Mardi | Jeudi</jour><heure>10:23</heure></horaire><horaire id="66916df97b043"><jour>Mercredi | Samedi</jour><heure>10:14</heure></horaire></horaires></paragraphe></description></film></cinema>
